config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  devise_for :users, controllers: { registrations: "registrations" }
  
  root 'pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:title, :name, :email, :company, :location, :discription)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  

  private

  def sign_up_params
    params.require(:user).permit(:email, :password)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :current_password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Real Experts", root_path, class: "navbar-brand" %>
    

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

    
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search for experts">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
         <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Signup", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">

  <% flash.each do |type, message| %>
    <div class="alert alert-info fade-in">
    <button class="close" data-dismiss="alert">x</button>
<%= message %>
    </div>
    <% end %>

<%= yield %>

</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Real Experts.</h1>

     <p>Get your project off the ground with the real experts.<br>
  Work With the Best Engineers, Architects & Surveyors</p>
  
  <br>
    
      
       <p><%= link_to "Create Your Profile",  new_user_registration_path, class: "btn btn-success btn-lg" %> </p>    
</div>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :company %>
    <%= f.input :location %>
    <%= f.input :discription %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.title %></td>
        <td><%= profile.name %></td>
        <td><%= profile.email %></td>
        <td><%= profile.company %></td>
        <td><%= profile.location %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
<%= link_to 'New Profile', new_profile_path %>
<% end %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @profile.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @profile.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @profile.location %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @profile.discription %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>